modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
license="GNU General Public License v3.0" #mandatory
issueTrackerURL="https://github.com/ToMe25/LootingVI/issues"
[[mods]] #mandatory
    modId="lootingmod" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Looting VI Mod" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/lootingvi"
    credits="issizk1ng - Turkish translation"
    authors="ToMe25"
    description='''A mod that allows you to set the max level for all vanilla enchantments that are made in a way that the level matters.'''
[[dependencies.lootingmod]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lootingmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
